#!/usr/bin/env python3
"""Lists the ribbon's text for translators.

The ribbon's labels live in resources/ribbon.json, where Qt's lupdate can't
see them. This writes src/app/ribbon_strings.cpp, which marks each one with
QT_TRANSLATE_NOOP("Ribbon", ...) so lupdate gathers them; the ribbon builder
translates them with the same context. Run it after changing the file's
text (the test ribbonStringsListed checks that it's current):

    python3 tools/ribbon_strings.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEYS = ("name", "text", "launcherTip", "tip", "label", "section", "submenu", "context")


def strings(node, out):
    if isinstance(node, dict):
        for k, v in node.items():
            if k in KEYS and isinstance(v, str) and v:
                out.add(v)
            strings(v, out)
    elif isinstance(node, list):
        for v in node:
            strings(v, out)


def main():
    with open(os.path.join(ROOT, "resources", "ribbon.json"), encoding="utf-8") as f:
        data = json.load(f)
    found = set()
    strings(data, found)
    lines = [
        "// Generated by tools/ribbon_strings.py from resources/ribbon.json: the",
        "// ribbon's text, marked so lupdate gathers it for translators. Don't edit.",
        "",
        "#include <QtGlobal>",
        "",
        "[[maybe_unused]] static const char *const kRibbonStrings[] = {",
    ]
    for s in sorted(found):
        lines.append('    QT_TRANSLATE_NOOP("Ribbon", %s),' % json.dumps(s, ensure_ascii=False))
    lines.append("};")
    with open(os.path.join(ROOT, "src", "app", "ribbon_strings.cpp"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(len(found), "strings")


if __name__ == "__main__":
    main()
